project:
  type: website
  output-dir: docs

website:
  title: "[Voltar ao site]"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: python-machine-learning.md
        text: "Machine Learning (ECG)"
      - href: equacoes-diferenciais-na-saude.md
        text: "Equações Diferenciais na Saúde"

format:
  html:
    theme:
      light: [default, custom-theme-light.scss]
      dark: [dark, custom-theme-dark.scss]
    css: styles.css
    toc: true
    code-fold: true
    include-after-body:
      - text: |
          <script>
          document.addEventListener("DOMContentLoaded", function() {
            const brand = document.querySelector(".navbar-brand");
            if (brand) {
              brand.href = "../";
            }
          });
          </script>
